############################################################################
# AI Scene-Aware Smart Speaker - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = scene_aware_speaker
PRIORITY  = $(CONFIG_SCENE_AWARE_SPEAKER_PRIORITY)
STACKSIZE = $(CONFIG_SCENE_AWARE_SPEAKER_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_SCENE_AWARE_SPEAKER)

MAINSRC = scene_aware_speaker_main.c

include $(APPDIR)/Application.mk
